version: '3.8'
services:

  db:
    image: postgres:latest
    container_name: study_jwt_postgres
    restart: always
    environment:
      POSTGRES_USER: studyjwt
      POSTGRES_PASSWORD: studyjwt
      POSTGRES_DB: study_jwt_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: